#!/usr/bin/env python

import rospy
from mushr_base.joy_teleop import JoyTeleop, JoyTeleopException


if __name__ == "__main__":
    try:
        rospy.init_node("joy_teleop")
        jt = JoyTeleop()
        rospy.spin()
    except JoyTeleopException:
        pass
    except rospy.ROSInterruptException:
        pass
