#!/usr/bin/python3

# Copyright (c) 2022, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import rospy
from threading import Thread
from mushr_base.nav_msg_converter import NavMsgConverter


class ConverterThread(Thread):
    def __init__(self):
        super(ConverterThread, self).__init__()

    def run(self):
        self.converter = NavMsgConverter()

    def shutdown(self):
        self.converter.root.quit()
        super(ConverterThread, self).shutdown()


def main():
    rospy.init_node("nav_msg_converter")

    converter_thread = ConverterThread()
    converter_thread.start()
    # Spin the main thread
    rospy.spin()
    # We either got SIGINT from control-C or ROS is otherwise coming down.
    converter_thread.converter.shutdown()


if __name__ == "__main__":
    main()
